
// languages.ts
export const languages = {
  en: {
    greeting: "Welcome",
    Home: "Home",
    instructors:'instructors',
    myLearning: "MyLearning",
    TechHeader: "Tech Header",
    EnrolledCourses:'Enrolled Courses',
    ContactUS: "Contact US",
    Profile:'Profile',
    Editing:'Editing',
    Settings:'Settings',
    Languages:'languages',
    Logout:'Logout',
    welcomeBack:'Welcome Back',
    start:'Lets start learning',
    learningNext:'What to learn next',
    min:'4 min left',
    causeViewed:'Because you viewed',
    recomended:'Recomended For You',
    recomendedForRating:'Recomended For You Based On Your Rating',
    LearnersAreView:'Learners are viewing',
    sweetVideos:'Short and sweet courses for you',
    personalRecommend:'Personalized recommendations',
    newWeb:'Newest courses in Web Development',
    meetInstructors:'Meet Our Instructors',
    instructorDes:'Here where you can find all our clevers instructors , feel free to keep in touch',
    education:'Education',
    university:'University',
    feedback:'Feedback and Reviews',
    description:'Description',
    requirments:'Requirements',
    content:'Course Content',
    previewCourse:'Preview This Course',
    addToCart:'Add to Cart',
    allCourses:'All Courses',
    myList:'My List',
    fav:'Favorites',
    learningTools:'Learning Tools',
    schedual:'Schedual Learning Time',
    learningDesc:'Learning a little each day adds up. Research shows that students who make learning a habit are more likely to reach their goals. Set time aside to learn and get reminders using your learning schedual',
    recentlyAccessed:'Recently Accessed',
    category:'Category',
    progress:'Progress',
    organize:'Organize and access your courses faster!',
    goToCourses:'Go to All Courses Tab',
    createCourse:'to create a list',
    FavCourses:'Your Favorites Courses',
    learningReminders:'Learning Reminders',
    calender:'Calendar events',
    ToolsDesc:'Learning a little each day adds up. Research shows that students who make learning a habit are more likely to reach their goals. Set time aside to learn and get reminders using your learning scheduler.',
    comeTech:'Come Tech With US',
    BecomeTech:'Become an instructor and change lives — including your own',
    getStarted:'Get Started',
    soManyReasons:'So many reasons to start',
    HowToBegin:'How To Begin',
    alone:'You won’t have to do it alone',
    contact:'Connecting people with knowledge',
    OurOrigin:'Our origins',
    HowWeStart:'How We Are Started',
    offices:'Our Offices',
    cart:'Your Cart',
    ShoppingCart:'Shopping Cart',
    coursesinCart:'0 Courses In Your Cart',
    keepShopping:'Your courses is empty. Keep shopping to find a course!',
    KeepBtn:'KeepShopping'
    
  },
  it: {
    greeting: "benvenuta",
    Home: "principale",
    instructors:'istruttori',
    myLearning:'il mio apprendimento',
    TechHeader: "Intestazione tecnica",
    EnrolledCourses:'Corsi iscritti',
    ContactUS:'contattaci',
    Profile:'profilo',
    Editing:'modifica',
    Settings:'impostazioni',
    Languages:'lingue',
    Logout:'disconnettersi',
    welcomeBack:'Bentornato',
    start:'Iniziamo ad imparare',
    learningNext:'cosa imparare dopo',
    min:'4 minuti rimasti',
    causeViewed:'Perché hai visualizzato',
    recomended:'Consigliato per te',
    recomendedForRating:'Consigliato a te in base alle valutazioni',
    LearnersAreView:'Gli studenti stanno visualizzando',
    sweetVideos:'Corsi brevi e dolci per voi',
    personalRecommend:'Raccomandazioni personalizzate',
    newWeb:'I corsi più recenti in Sviluppo Web',
    meetInstructors:'Incontra i nostri istruttori',
    instructorDes:"Qui dove puoi trovare tutti i nostri abili istruttori, sentiti libero di restare in contatto",
    education:'istruzione',
    university:'Università',
    feedback:'FeedBack e recensioni',
    description:'Descrizione',
    requirments:'Requisiti',
    content:'Contenuto del corso',
    previewCourse:'vedere in anteprima questo corso',
    addToCart:'Aggiungi al carrello',
    allCourses:'Tutti i corsi',
    myList:'la mia lista',
    fav:'preferiti',
    learningTools:'strumenti di apprendimento',
    schedual:'Pianifica il tempo di apprendimento',
    learningDesc:'Imparare un po ogni giorno aiuta. La ricerca mostra che gli studenti che fanno dell’apprendimento un’abitudine hanno maggiori probabilità di raggiungere i propri obiettivi. Metti da parte del tempo per imparare e ricevere promemoria utilizzando il tuo programma di apprendimento.',
    recentlyAccessed:'Accesso recente',
    category:'Categorie',
    progress:'progressi',
    organize:'Organizza e accedi più velocemente ai tuoi corsi!',
    goToCourses:'Vai alla scheda Tutti i corsi',
    createCourse:'per creare un elenco.',
    FavCourses:'I tuoi corsi preferiti',
    learningReminders:'Promemoria per l apprendimento',
    calender:'Eventi del calendario',
    ToolsDesc:'Imparare un po ogni giorno aiuta. La ricerca mostra che gli studenti chirendere l’apprendimento un’abitudine hanno maggiori probabilità di raggiungere i propri obiettivi. Imposta l orada parte per imparare e ricevere promemoria utilizzando il tuo programma di apprendimento.',
    comeTech:'Vieni a insegnare con noi',
    BecomeTech:'Diventa un istruttore e cambia vita - incluso il tuo',
    getStarted:'iniziare',
    soManyReasons:'Tanti motivi per iniziare',
    HowToBegin:'Come iniziare',
    alone:'Non dovrai farlo da solo',
    contact:'Connettere le persone con la conoscenza',
    OurOrigin:'Le nostre origini',
    HowWeStart:'Come abbiamo iniziato',
    offices:'I nostri uffici',
    cart:'il tuo carrello',
    ShoppingCart:'Carrello della spesa',
    coursesinCart:'0 corsi nel carrello',
    keepShopping:'I tuoi corsi sono vuoti. Continua a fare acquisti per trovare un corso!',
    KeepBtn:'Continua a fare acquisti'
  },
};
