import { Provider } from "@/components/ui/provider";
import ReduxProvider from "./components/ReduxProvider";
import localFont from "next/font/local";
import { NextUIProvider } from '@nextui-org/react';  // Import NextUI
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <MainComponent>{children}</MainComponent>
    </ReduxProvider>
  );
}

const MainComponent: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  "use client";

  return (
    <html suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
          <Toaster position="top-right"/>
          <NextUIProvider>
            <div>{children}</div>
          </NextUIProvider>
        </Provider>
      </body>
    </html>
  );
};
